### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by chriskonnertz** [Usbac/Wolff#10]
Just some thoughts...

- Global constants ( https://github.com/Usbac/Wolff/blob/master/config.php ) obviously can conflict with global constants defined by third party libraries. Yes ofcourse it is more handy to only write `echo PAGE_TITLE` instead of `echo  $this->config->get('page_title')` or whatever, but I don't think having a global constant called `PASSWORD` is a good idea. Password of what? If you would create a separate config file for the database config and use something else than global constants it would be unique and not causing any conflicts due to ambiguity.
- The folder `app/controller` contains multiple controller**s** so why not name it `app/controllers`?
- It's a convention that class names always should start with an uppercase letter ( for instance `Home` instead of `home` => https://github.com/Usbac/Wolff/blob/master/app/controller/home.php#L5) 
- You might consider to use type hint annotations also on class properties, for instance: `/** Core\Cache */ public $cache;` instead of just `public $cache;` ( https://github.com/Usbac/Wolff/blob/master/system/Start.php#L11 )

I think the things that I mentioned are more or less conventions. It makes it easier for other coders to read and understand code if these conventions are followed.

**Comment by Usbac** [comment]
Thank you so much for your conventions! they are highly appreciated :)

* The App subfolders were renamed as you say.
* Class names now starts with an uppercase letter.
* The global constants have a more explicit name.

The type hint annotations will be applied in the next commit, quite soon.
Greetings.

**Comment by chriskonnertz** [comment]
Great! :)
