### ISSUE TITLE
Make template engine recursive

### ISSUE THREAD

**Issue by siteantipas** [Usbac/Wolff#12]
Hi again, I have been wondering how possible is it for you to make the template engine syntax to be valid on included PHP files also.

- For example, the home controller loads the `app/views/home.php`
- Suppose I include a file `nav.php` from the `home.php` view
- It would be nice if the syntax, say `{{ $language['welcome'] }}` be available in this `nav.php` included file.

Thank you

**Comment by Usbac** [comment]
The template engine is actually recursive :)

If you use the template load tag instead of the php include tag (like this: `@load(nav.php)`), that will replace the load tag with that view content, making the syntax available to the included file.

Greetings!
