### ISSUE TITLE
Community libraries

### ISSUE THREAD

**Issue by beganovich** [Usbac/Wolff#15]
Hello, and thanks for such a simple tool to work with.

I was wondering, since main framework does not have any 3rd-party dependencies included, does it have to stay like that in future? I planned some PRs, so I am asking.

Thanks 👍

**Comment by Usbac** [comment]
Hello, yes currently Wolff doesn't depend on 3rd-party components but it doesn't have to stay like that.
So it's open to changes :)

Greetings!

**Comment by beganovich** [comment]
Thanks! 👍
