### ISSUE TITLE
Wrong folder name in Routes Creation from cli

### ISSUE THREAD

**Issue by biswajitpaul01** [Usbac/Wolff#16]
I like your framework. It is small & fast. I would like to fix a cli command issue given below:

~~~bash
$ php Wolffie mk route page pages/contact
PHP Warning:  fopen(System/definitions/Routes.php): failed to open stream: No such file or directory in /var/www/html/samples/php/wolff/system/cli/Create.php on line 226
~~~

On line 19 in system/cli/Create.php, folder **System** should be **system**.
~~~php
$this->routes_dir = 'System/definitions/Routes.php';
~~~
to
~~~php
$this->routes_dir = 'system/definitions/Routes.php';
~~~

**Comment by Usbac** [comment]
Hi @biswajitpaul01, thank you so much for pointing out that issue. 
I just fixed it :)

Greetings!

**Comment by biswajitpaul01** [comment]
@Usbac Thanks for quick fix. One thing I am missing is clearing all/partial cache from CLI. Can this be included in next version?

**Comment by Usbac** [comment]
Yes, that seems like a very good idea! I will try to include it in the next commit.

**Comment by biswajitpaul01** [comment]
@Usbac You are welcome.

**Comment by Usbac** [comment]
Done! Now all/partial cache files can be deleted or listed throught the CLI.

https://github.com/Usbac/wolff-framework/commit/7129d0421f3643227567a145c3be781d6914bb38

**Comment by biswajitpaul01** [comment]
@Usbac That's great progress. Keep it up.
