### ISSUE TITLE
Make an auth API or functionality

### ISSUE THREAD

**Issue by siteantipas** [Usbac/wolff#18]
The framework is great! I remember back a few months when it started and I had to download the first version and use it for a project.

I will like you to implement an auth functionality similar to `php artisan make:auth`  [https://laravel.com/docs/5.7/authentication](url) to make the developing phase faster and sweeter ;-) for developers like me.

Thanks

**Comment by Usbac** [comment]
Hi @siteantipas I'm glad you like it :)

Currently the CLI of wolff has been removed because it's being partially remade, I like your Auth idea so most probably it will be implemented in the next launch of the CLI.

Greetings

**Comment by Usbac** [comment]
Hi @siteantipas, I'm glad to announce you that the Auth utility has been added to Wolff and is available at the version 2.4. :)

commit: https://github.com/Usbac/wolff-framework/commit/ae05be73bf7b04dbf125bc86d90978ea6c9b9010

docs: http://getwolff.com/doc/2.x/auth

**Comment by siteantipas** [comment]
Wow, great news. I can now use the updated versions for upcoming projects.
Great job
