### ISSUE TITLE
How to run on localhost

### ISSUE THREAD

**Issue by surebro00** [Usbac/wolff#20]
Hi, 

I've seen your simple but amazing Wolff framework and I would like to know how to run the project on my localhost.
I'm able to use XAMPP or Vagrant Homestead for PHP projects.
Remember to upgrade your documentation ;)

Many thanks, 
Keep going with your framework!

**Comment by pablomarcano16** [comment]
Hello, if you simply copy your project folder and paste it on your local server (XAMPP, WAMP, Laragon, etc). Remember to have a version of PHP 7.0 onwards.

**Comment by xewl** [comment]
Or just use PHP's [built-in web server](https://www.php.net/manual/en/features.commandline.webserver.php).

`$ cd ~/public_html`
`$ php -S localhost:8000`

**Comment by Usbac** [comment]
Thank you for pointing out it! I have upgraded the documentation :).
Now you can see how to run Wolff on localhost here: https://github.com/Usbac/wolff/wiki/Installation
