### ISSUE TITLE
Installing via composer has no version

### ISSUE THREAD

**Issue by siteantipas** [Usbac/wolff#22]
I wish to point out that on both version 1.x and 2.x installation pages, [https://www.getwolff.com/doc/1.x/installation](url) and [https://www.getwolff.com/doc/2.x/installation](url)

The commands to install **Wolff** via composer are all the same
`composer create-project usbac/Wolff`

- The question is: **how do we specify the version we wish to install in the composer command?** 

- May be you could precise these different commands on both installation pages?

- Maybe something like `composer create-project usbac/Wolff -v 1.x` and 
`composer create-project usbac/Wolff -v 2.x`

Thank you

**Comment by Usbac** [comment]
Done! Now the install page of the 1.x version specifies the version in the command.
https://getwolff.com/doc/1.x/installation

Basically the command is this: `composer create-project usbac/wolff wolff "1.*"`.

The same will happen with the 2.x version when a 3.x version comes out. Thank you!

**Comment by siteantipas** [comment]
Oh great, so what's the command to install version 2.x right now?
Is it simply

- `composer create-project usbac/wolff`

...without precising the version so it installs version 2.x automatically?
Thank you

**Comment by Usbac** [comment]
Yes! Running the composer command without specifying the version will download the last stable version of Wolff, which is currently 2.6. :)

When a 3.x version comes out, I'll change the command in the documentation to `composer create-project usbac/wolff wolff "2.*"` so that it only downloads the last 2.x version.
