### ISSUE TITLE
Could you add the vendor folder to the .zip installation?

### ISSUE THREAD

**Issue by siteantipas** [Usbac/wolff#23]
- I wish to suggest that you add the `vendor` folder and any other dependencies of `wolff framework` in it's classic .zip download file at [https://github.com/Usbac/wolff/archive/v2.6.zip](url)

- To me, it is better so anyone who chooses to download the zip file (instead of installing via composer) will not have to run `composer install` to get the `vendor` and all dependencies. 

- It will make `wolff framework` really easy to install and accessible to even the most beginners in PHP who don't know how to use composer.

Thanks

**Comment by Usbac** [comment]
Done! :) That's a great idea so now the future versions will include the bundle zip too.

https://github.com/Usbac/wolff/releases/download/v2.6/wolff-bundle.zip
