### ISSUE TITLE
Parameters in URI get lowercased

### ISSUE THREAD

**Issue by loulou2852** [Usbac/wolff#24]
Hello Wolff Team,

I try to get the URI parameter in order to check a product, but the request get automatically lowercased.
![uri-lower](https://user-images.githubusercontent.com/4818634/75794104-9e31b700-5d70-11ea-89d9-35b0b3588fb8.png)

This is the sample code I used:

![uri-lower-code](https://user-images.githubusercontent.com/4818634/75794328-ec46ba80-5d70-11ea-94c0-eb772049f1a0.png)

The problem is it has to be case sensitive in order to catch the real id.
I didn't find anything in the doc.

Do you know if you can have an option to keep it case sensitive?

Thanks for your awesome job.

Regards.

Louis

**Comment by Usbac** [comment]
Hello Louis! Thank you for pointing out that detail, it has been fixed so now the request url isn't lowercased. The change is available in the new 2.7 version. You are at one `composer update` command away :)
Regards.

https://github.com/Usbac/wolff-framework/commit/2d6b2e3ac433fd38bed330a8f1c3f38903ffdebb
