### ISSUE TITLE
Internal Server Error on Linux (due to File Permission)

### ISSUE THREAD

**Issue by siteantipas** [Usbac/wolff#29]
The Wolff project generates an **Internal Server Error** once installed on non-Windows servers which makes it impossible to use framework.
After troubleshooting, I figured out the issue: 
`/public/index.php" is writeable by group` is the error thrown on linux hosting servers. 

- This happens because the above mentioned file in `/public/index.php` has a permission of `0777` and it looks like Linux servers don't support that for some reason

- My suggestion is that you recursively change the file permission for each `Wolff` files (to say `0755`) so this issue gets resolved in future releases.

Thank you

**Comment by Usbac** [comment]
Hello @siteantipas! Thank you for pointing that out, the recommended file permissions for the Wolff source code files is in fact 0755. What I've been able to see is that this is happening only with the bundle version of Wolff, so I'll update it.

I'll also update the documentation and specify there this required file permissions.

Greetings! :)

**Comment by Usbac** [comment]
The bundle package and the documentation has been correctly updated.
