### ISSUE TITLE
Website gone 

### ISSUE THREAD

**Issue by mw75** [Usbac/wolff#36]
The Website 
https://www.getwolff.com/
http://www.getwolff.com/
https://getwolff.com/
http://getwolff.com/
is not reachable. The missing/broken links in the documentation makes it hard to read.

I would like to compare wolff with SlimPHP. Has anyone already made and documented this comparison?

**Comment by Usbac** [comment]
The website is now back! There was a little problem with the domain and its payment.

And thank you about the comparison idea 😄, a comparison page will be made and added to the official documentation in the next days explaining the differences between Wolff and other PHP frameworks.

**Comment by siteantipas** [comment]
Dear Usbac/wolff,
Your Framework is amazingly easy/fast to integrate and work with. Once
more, thumbs up. I will suggest you create a Tipeee kind of page, a PayPal
Donate or something. Anything that can be put on the website so people can
at free will send you
some funds as support to the great work you are doing.

**Comment by Usbac** [comment]
@siteantipas Thank you so much for your kind messages! 😃 

A donation option has been added to the footer of getwolff.com, in the future this option will be improved.

**Comment by siteantipas** [comment]
Awesome.

**Comment by Usbac** [comment]
@mw75 The comparison has been added to the documentation as a question in the FAQ page. 😃 

b09d9834c237303a655812ecb499aaefcfa0eb51
