### ISSUE TITLE
Is there a fully functioning example project using this Framework?

### ISSUE THREAD

**Issue by TheMashaBrand** [Usbac/wolff#37]
Hi, I have checked out the Framework and it is well organized and easy to understand. 

What I am wondering is if there is an example project built with this framework so we can get to understand the code much better.

Thanks.

**Comment by Usbac** [comment]
Hello @TheMashaBrand! Thank you for your interest, the wolff website itself is made with Wolff (but hosted on GitLab).

The project doesn't use "all" of the framework features but I hope it serves well as an example. :smile:

https://gitlab.com/Usbac/getwolff.com
