### ISSUE TITLE
A route with the same name cannot be defined

### ISSUE THREAD

**Issue by wfsdaj** [Usbac/wolff#39]
Sorry, my English is not good. -_-''

for example:

Route::get('/login',  [ Controllers\User::class, 'showLoginForm' ]);
Route::post('/login', [Controllers\User::class, 'login']);

**Comment by Usbac** [comment]
Hello! It's not possible to define two routes with the same name due to the way the router works internally, but don't worry, the same functionality can be accomplished with the following code:

```php
Route::any('/login', function($req, $res) {
    switch ($req->getMethod()) {
        case 'GET': call_user_func_array([ Controllers\User::class, 'showLoginForm' ], [ $req, $res ]);
            break;
        case 'POST': call_user_func_array([ Controllers\User::class, 'login' ], [ $req, $res ]);
            break;
        default: $res->setCode(404);
    }
});
```
