### ISSUE TITLE
No command to install via Composer

### ISSUE THREAD

**Issue by siteantipas** [Usbac/Wolff#4]
I have been wanting to install Wolff via composer with no avail.
I tried the following in command line:
`composer require Wolff`
The command to install should be in the Wiki pages, I suggest.

**Find below is a screenshot explaining the issue in details:**
![capture](https://user-images.githubusercontent.com/24583854/53923911-3754c180-407a-11e9-9681-5441b9398b1c.PNG)

**Comment by Usbac** [comment]
Done, thanks!
[Wolff - Installation](https://github.com/Usbac/Wolff/wiki/Installation) :)
