### ISSUE TITLE
Can session support setting arrays?

### ISSUE THREAD

**Issue by wfsdaj** [Usbac/wolff#40]
for example:

```
public static function set($param,$value=false): void
  {
    if (is_array($param)) {
      foreach ($param as $key => $value) {
        $_SESSION[$key]=$value;
      }
    }
    else {
      $_SESSION[$param]=$value;
    }
  }
```

**Comment by Usbac** [comment]
Thanks for the suggestion! 😄  But due to the way the Wolff's session API works, it's not possible to support something like that without breaking backward compatibility, and setting session data with arrays can be implemented with a simple foreach written by the user.
