### ISSUE TITLE
env override => true does not affect maintenance_on

### ISSUE THREAD

**Issue by sephentos** [Usbac/wolff#42]
```
<?php

return [
    'db' => [
        'dsn'      => '',
        'username' => '',
        'password' => '',
    ],

    'env' => [
        'file'     => 'system/.env',
        'override' => true,
    ],

    'language'       => 'en',

    'development_on' => true,
    'template_on'    => true,
    'cache_on'       => true,
    'stdlib_on'      => true,
    'maintenance_on' => false,
];
```
The maintenance page is not calling up when having `maintenance_on` => `true` in the .env file and `env.override` => `true` while `maintenance_on` => `false` in the config.php

`Config::get('maintenance_on')` also correctly returns `true`

Setting maintenance to true in the config file results in showing the maintenance page back again but it should already have been shown with maintenance_on set to true in the .env file, or not?

**Comment by Usbac** [comment]
It has been fixed in the new version [4.1.0](https://github.com/Usbac/wolff-framework/releases/tag/v4.1.0)!

Thank you so much for pointing out this bug. 😄
