### ISSUE TITLE
Can Middleware have $res? / Always add JSON content-type

### ISSUE THREAD

**Issue by sephentos** [Usbac/wolff#43]
I'd like to achieve that every route within a given subdirectory should have

```
    $res->setHeader('Content-Type', 'application/json');
```

Currently I need to use setHeader for every route.

Something like this would be great; Alternatively, I am of course open for feedback how it would otherwise work.

```
Middleware::before('/api', function($req, $next, $res) {
    $res->setHeader('Content-Type', 'application/json');
});
```

(Maybe it would also be an idea that writeJson() would add this header automatically, at least via a controllable parameter?)

**Comment by Usbac** [comment]
Hello @sephentos, thank you for pointing out that improvement, it has been done in the new version [4.1.0](https://github.com/Usbac/wolff-framework/releases/tag/v4.1.0)!

Now middleware closures can take a third parameter with the response object.

Just remember to run a `composer update`. 😄

**Comment by sephentos** [comment]
Hey @Usbac !
Thank you very much for the very quick fix! :)

Just one more little thing (really not important!): The middleware does not intervene with Route::code or Maintenance::set when making them listen to `*`. 
See example:

```
Middleware::before('*', function($req, $next, $res) {
    $res->setHeader('Content-Type', 'application/json');
});

// works fine, content-type is application/json
Route::get('/', function ($req,$res) {
    $res->writeJson([ 'test' => 'test']);
});

// does not work, middleware not being applied
Route::code(404, function ($req,$res) {
    $res->writeJson([ 'test' => 'test']);
});

// does not work, middleware not being applied
Maintenance::set(function($req, $res) {
    $res->writeJson([ 'test' => 'test']);
});
```
To be fair, thats a very simple example in which I could copypaste setHeader to both, but I was thinking about adding more stuff into the middleware later.

I guess that it would not be so easy to set the routing (`Middleware::before('*'`) of the middleware for a 404 or maintenance. Would it otherwise be possible to call the middleware within the 404 / maintenance functions by some way?

**Comment by Usbac** [comment]
You're welcome @sephentos! :) 

The code routes have a higher hierarchy than the middlewares, and the maintenance mode does not take into account the middlewares, sorry about that detail.

I have been thinking about changing it but such change would break backward compatibility so for now it's reserved for the version 5.0.

**Comment by sephentos** [comment]
Alright! Thanks for the reply.
(Also being already hyped for 5.0, really loving your work 😊)
