### ISSUE TITLE
Improve on the naming convention

### ISSUE THREAD

**Issue by siteantipas** [Usbac/Wolff#5]
This framework is amazing, @Usbac 

1. I suggest that files should be named according to what they do as it will be more descriptive.
 For example:  `home.controller.php` , `home.model.php` and `home.view.php`

2. Secondly, an `assets` folder should be created in the `app` folder to contain images, css, js and other files rather than being in the `views` folder.

**assets**
`-- images`
`-- css`
`-- js`

**Comment by Usbac** [comment]
1.- The files doesn't have a more descriptive name to avoid word repetition, and for that there is the use of namespaces. But thanks anyway! That could change in the future.

2.- Good idea! the assets folder is now done :)
