### ISSUE TITLE
Route with parameter redirects to 404 Page

### ISSUE THREAD

**Issue by siteantipas** [Usbac/Wolff#8]
The previous version had the route parameter working fine for me, not this one.

When adding a parameter in the Routes.php file, 

Route::add('main_page/{username}', function (){
     
/* 
This route is ignored and it loads the 404 page.
 */

});

If the parameter is added without the 'main_page', it throws a fatal error.
For example

Route::add('/{username}', function (){
     
/* 
This route will throw a fatal error.
 */

});

**Comment by Usbac** [comment]
Fixed! Thank you for letting me know about the error :)
